import { test, expect } from '@playwright/test'
import { onboard } from './helpers/onboard'

test('week of real diary use: backdate, copy, edit, reload, review and save a complete meal', async ({ page }) => {
  test.setTimeout(90000)
  const pageErrors: string[] = []
  page.on('pageerror', (error) => pageErrors.push(error.message))
  await onboard(page, { fixedTime: new Date('2026-09-08T02:00:00'), name: 'Weekly Reviewer' })
  // Enter six historical days through the visible date picker and logging actions.
  for (let i = 0; i < 6; i++) {
    const date = `2026-09-0${i + 2}`
    await page.getByTestId('tab-log').click()
    await page.getByLabel('Choose diary date').fill(date)
    await page.getByTestId('fab-scan').click()
    await expect(page).toHaveURL(new RegExp(`date=${date}`))
    await page.getByTestId('page-custom-button').click()
    await page.getByLabel('Name', { exact: true }).fill(`Lunch day ${i + 1}`)
    await page.getByLabel('Calories (kcal)').fill(String(450 + i * 10))
    await page.getByLabel('Protein (g)').fill('25')
    await page.getByLabel('Carbs (g)').fill('50')
    await page.getByLabel('Fat (g)').fill('15')
    await page.getByLabel('Fiber (g)').fill('6')
    await page.getByRole('button', { name: 'Add to Breakfast', exact: true }).click()
    await expect(page).toHaveURL(`/log?date=${date}`)
    await expect(page.getByTestId('diary-day-total')).toContainText(`${450 + i * 10} kcal`)
  }
  await page.getByTestId('tab-today').click()
  await page.getByTestId('copy-yesterday-confirm').click()
  await expect(page.getByTestId('figure-eaten').locator('p').first()).toHaveText('500')
  await expect(page.getByTestId('weekly-diary-card')).toContainText('7 / 7 days logged')
  await expect(page.getByTestId('fiber-bar-value')).toContainText('6 /')
  await page.reload()
  await expect(page.getByTestId('figure-eaten').locator('p').first()).toHaveText('500')
  // Yesterday remains independent after copying today and editing the original.
  await page.getByRole('button', { name: 'Previous day', exact: true }).click()
  await page.getByRole('button', { name: 'Edit Lunch day 6' }).click()
  await page.getByTestId('entry-detail-edit-button').click()
  await page.getByLabel('Calories (kcal)').fill('550')
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(page).toHaveURL('/log?date=2026-09-07')
  await expect(page.getByTestId('diary-day-total')).toContainText('550 kcal')
  await page.getByTestId('tab-today').click()
  await expect(page.getByTestId('figure-eaten').locator('p').first()).toHaveText('500')
  // A custom entry is part of a saved meal; it must not silently disappear.
  await page.getByTestId('tab-log').click()
  await page.getByTestId('meal-overflow-breakfast').click()
  await page.getByRole('button', { name: /Save as template/i }).click()
  await page.getByLabel('Template name').fill('Weekday lunch')
  await page.getByRole('button', { name: 'Save template', exact: true }).click()
  await expect(page).toHaveURL('/templates')
  await page.goto('/templates?date=2026-09-02')
  await expect(page.getByTestId('templates-list')).toContainText('1 item')
  await page.getByRole('button', { name: 'Log now', exact: true }).click()
  await expect(page).toHaveURL('/log?date=2026-09-02')
  await expect(page.getByTestId('diary-day-total')).toContainText('950 kcal')
  await page.goto('/trends/report')
  await expect(page.getByTestId('report-avg-kcal')).toHaveText('557.1 kcal')
  expect(pageErrors).toEqual([])
})

test('phone date context, modal keyboard focus, decimal nutrients and invalid dates', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await onboard(page)
  await page.getByTestId('fab-scan').click()
  await expect(page.getByTestId('bottom-sheet')).toBeVisible()
  await page.getByRole('button', { name: 'Close', exact: true }).focus()
  await page.keyboard.press('Shift+Tab')
  expect(await page.getByTestId('bottom-sheet').evaluate((el) => el.contains(document.activeElement))).toBe(true)
  await page.keyboard.press('Escape')
  await expect(page.getByTestId('bottom-sheet')).not.toBeVisible()
  await page.goto('/log/quick-add?date=2026-02-31')
  await page.getByLabel('Name', { exact: true }).fill('Decimal snack')
  await page.getByLabel('Calories (kcal)').fill('125.5')
  await page.getByLabel('Protein (g)').fill('10.5')
  await page.getByLabel('Fiber (g)').fill('2.5')
  await page.getByRole('button', { name: 'Add to Breakfast', exact: true }).click()
  await expect(page).toHaveURL('/')
  await expect(page.getByTestId('figure-eaten').locator('p').first()).toHaveText('126')
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)
  expect(overflow).toBe(false)
})
